version: '3'
services:
  tdd_postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /tmp
    volumes:
      - C:\Users\gleys\postgres:/var/lib/postgresql/data
    restart: unless-stopped

  tdd_pgadmin:
    image: dpage/pgadmin4
    links:
      - tdd_postgres
    depends_on:
      - tdd_postgres
    volumes:
      - C:\Users\gleys\postgres:/root/.pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gleysonpc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin: